# 应用名称
server:
  port: 8800
spring:
  devtools:
    livereload:
      enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: Senbei-forum-main
    # DataSource Config
    #邮箱发送配置
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 1983890621@qq.com
    password: emeamrhnsomceece
    smtp:
      auth: true
      starttls:
        enable: true
        request: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  typeAliasesPackage: com.yhz.senbeiforummain.model # 搜索指定包别名

jasypt:
  encryptor:
    # 配置加密算法
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: yhz
    property:
      # 算法识别前缀(当算法发现配置文件中的值以这前缀开始，后缀结尾时，会使用指定算法解密)
      prefix: IT(
      # 算法识别后缀
      suffix: )

jwt:
  # JWT存储的请求头
  tokenHeader: authorization
  # JWT 加解密使用的密钥
  secret: lzdwtl
  # JWT的超期限时间（1000*60*60*24*14）14天，即两周
  expiration: 1209600000
  # JWT 负载中拿到开头
  tokenHead: Bearer