# 应用名称
server:
  port: 8800
spring:
  application:
    name: Senbei-forum-main
    # DataSource Config
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/senbei_forum?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  profiles:
    active: dev
