#dubbo:
#  application:
#    name: dubbo-provider # dubbo应用名
#  registry:
#    address: zookeeper://127.0.0.1:2181?init.timeout=60000 # 注册中心url
#    protocol: zookeeper # 协议是zookeeper, 可以不写
#  scan:
#    base-packages: com.yhz.orderserviceconsumer.service.impl # 要扫描的包

logging:
  config: classpath:logback-spring.xml
#  level:
#    com.yhz.senbeiforummain.mapper: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  typeAliasesPackage: com.yhz.senbeiforummain.domain # 搜索指定包别名
#jasypt:
#  encryptor:
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator
#    algorithm: PBEWithMD5AndTripleDES
#    property:
#      prefix: ENC(
#      suffix: )

jasypt:
  encryptor:
    # 配置加密算法
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    property:
      # 算法识别前缀(当算法发现配置文件中的值以这前缀开始，后缀结尾时，会使用指定算法解密)
      prefix: IT(
      # 算法识别后缀
      suffix: )
spring:
  cloud:
    alicloud:
      access-key: IT(J9Zz9tGmGctFR6K61Jvq5KB4FsMjtLshGCoqhkCRx8HsthCTS6vmXw==)
      secret-key: IT(dTYd0BD0xedniWbVie43YMHEYEOv83lt+Cfu4umWu+WWDwgYWw08Nw==)
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
        bucket: mail-yhz