#dubbo:
#  application:
#    name: dubbo-provider # dubbo应用名
#  registry:
#    address: zookeeper://127.0.0.1:2181?init.timeout=60000 # 注册中心url
#    protocol: zookeeper # 协议是zookeeper, 可以不写
#  scan:
#    base-packages: com.yhz.orderserviceconsumer.service.impl # 要扫描的包

logging:
  config: classpath:logback-spring.xml
#  level:
#    com.yhz.senbeiforummain.mapper: debug


spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://111.230.243.152:3306/senbei_forum?serverTimezone=Asia/Shanghai
    username: root
    password: IT(uYTzWWdyGoG4ClQoSllzmQ==)
  #redis配置
  redis:
    #服务器地址
    host: 111.230.243.152
    #端口
    port: 6379
    #redis密码
    password: IT(uYTzWWdyGoG4ClQoSllzmQ==)
    #数据库，默认是0
    database: 0
    #超时时间
    timeout: 1209600000ms
    lettuce:
      pool:
        #最大链接数，默认8
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 5
  cloud:
    alicloud:
      access-key: IT(J9Zz9tGmGctFR6K61Jvq5KB4FsMjtLshGCoqhkCRx8HsthCTS6vmXw==)
      secret-key: IT(dTYd0BD0xedniWbVie43YMHEYEOv83lt+Cfu4umWu+WWDwgYWw08Nw==)
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
        bucket: mail-yhz
#  rabbitmq:
#    host: 192.168.0.193
#    port: 5672
#    virtual-host: /
#    publisher-returns: true #开启发送端确认
#    publisher-confirm-type: CORRELATED #开启发送端消息抵达队列的回调
#    template:
#      mandatory: true #只要抵达队列，以异步发送优先回调return confirm
#    listener:
#      simple:
#        acknowledge-mode: manual #手动确认消息




oauth:
  github:
    clientId: 59375e93fc8678305556
    clientSecret: IT(JhYVKBXcVstB+90aDUsP+SCXvE4T4OsHDPK5fXZL9wbrr4EqyY7F/DpnrDjqpfK73efpR2gfCKk=)
    redirectUri: http://111.230.243.152:8800/oauth/github/redirect
    frontRedirectUrl: http://111.230.243.152:9090/#/redirect
  gitee:
    clientId: cb6fe5b122d9f3d27fd86d2709255d25a1f34162d871d33cd27104f4b36a156c
    clientSecret: IT(v9iWgsrz/AwmVLC/WspVO1vtgblB8503t8EhbINb/NsE2wlf8XS+LWIY4/OxOB+34r0SeDT77a4tC7Hds8O4DKa19qYs4pyhNXFojM1nd8A=)
    redirectUri: http://111.230.243.152:8800/oauth/gitee/redirect
    frontRedirectUrl: http://111.230.243.152:9090/#/redirect